try {
    // 可能发生异常的程序语句
}
catch (ExceptionType1 exOb) {
    // 错误类型1处理语句
}
catch (ExceptionType2 exOb) {
    // 错误类型2处理语句
}
finally {
    // try语句结束后必须执行的代码
}
                     异常层次
                    Throwable
                 |              |
             Exception        Error (灾难性的失败)
      (用户程序应当捕获的异常或自定义异常)           
                 |              
          RuntimeException
 （自动定义的异常 such as 除零，无效数组索引）
 
 多条catch语句是，异常的子类一定要放在superclass之前
 catch (RuntimeException e){
    // body of catch
 }
 catch (Exception e) {               //如果颠倒两个catch，则RuntimeException会被 Exception
    // ...                           //导致到不了catch(RuntimeException)，编译报错
}
 
 throw ThrowableInstance 手动抛出异常
 
 
 
 
 
 
 
 
 
 
 
 